Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Lint/MissingSuper:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
