require:
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.3
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - script/**/*
    - vendor/**/*
    - log/**/*
    - .irbrc

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Lint/MissingSuper:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/**/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'app/controllers/**/*'
Metrics/MethodLength:
  Exclude:
    - 'app/controllers/**/*'
    - 'app/sidekiq/**/*'
Metrics/ClassLength:
  Exclude:
    - 'app/controllers/**/*'

Naming/VariableNumber:
  Enabled: false

Rails/FilePath:
  Enabled: false
Rails/OutputSafety:
  Exclude:
    - 'spec/**/*'

RSpec/ExampleLength:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/MultipleExpectations:
  Max: 2
  Exclude:
    - 'spec/system/**/*'
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Lambda:
  Enabled: false
