require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - script/**/*
    - vendor/**/*
    - log/**/*

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Lint/MissingSuper:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Lambda:
  Enabled: false
