ARG RUBY_VERSION=3.3.0

FROM ruby:$RUBY_VERSION-slim as base

RUN apt-get update -qq \
    && apt-get install --no-install-recommends -y build-essential ca-certificates curl gnupg locales libvips libpq-dev \
      libwebp-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists /var/cache/apt/archives

WORKDIR /rails

# Install Node and Yarn JS package manager
# See also https://github.com/nodesource/distributions#installation-instructions
ARG NODE_MAJOR=20
ARG YARN_VERSION=1.22.19
RUN mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${NODE_MAJOR}.x nodistro main" | \
    tee /etc/apt/sources.list.d/nodesource.list && \
    apt-get update && \
    apt-get install nodejs -y && \
    npm install -g yarn@$YARN_VERSION

# Install JS dependencies
FROM base as node

COPY package.json yarn.lock ./
RUN yarn install

# Install Ruby dependencies
FROM base as gems

COPY Gemfile Gemfile.lock ./
RUN gem install bundler && bundle install --jobs 20 --retry 5

# Final build
FROM base as build

WORKDIR /rails

RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8


COPY . ./
# Copy ruby and JS dependencies
COPY --from=gems /usr/local/bundle /usr/local/bundle
COPY --from=node /rails/node_modules /rails/node_modules

EXPOSE 3000

CMD ["bin/dev"]
