ARG RUBY_VERSION=3.2.2

FROM ruby:$RUBY_VERSION-slim as base

RUN apt-get update -qq \
    && apt-get install --no-install-recommends -y build-essential ca-certificates curl gnupg locales libvips libpq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists /var/cache/apt/archives

WORKDIR /app

# Install JS dependencies
# See also https://github.com/nodesource/distributions#installation-instructions
ARG NODE_MAJOR=20
ARG YARN_VERSION=1.22.19
RUN mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${NODE_MAJOR}.x nodistro main" | \
    tee /etc/apt/sources.list.d/nodesource.list && \
    apt-get update && \
    apt-get install nodejs -y && \
    npm install -g yarn@$YARN_VERSION

# Install node modules
COPY package.json yarn.lock ./
RUN yarn install

FROM base as gems

COPY Gemfile Gemfile.lock ./
RUN gem install bundler && bundle install --jobs 20 --retry 5

FROM base as build

WORKDIR /app

RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

COPY . ./
COPY --from=gems /usr/local/bundle /usr/local/bundle

EXPOSE 3000

CMD ["bin/dev"]
