development:
  adapter: redis
  url: <%= Rails.application.credentials[:redis_url] %>
  channel_prefix: tmp_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= Rails.application.credentials[:redis_url] %>
  channel_prefix: tmp_production
