default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= Rails.application.credentials[:postgres_host] %>
  user: <%= Rails.application.credentials[:postgres_user] %>
  password: <%= Rails.application.credentials[:postgres_password] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: tmp_development
test:
  <<: *default
  database: tmp_test
production:
  <<: *default
  database: tmp_production
  username: tmp
  password: <%= ENV['SUPER_SECRET_DATABASE_PASSWORD'] %>
